- name: Build a list of state gatherers
  set_fact:
    gather: "{{ available_gather|
                nmake.jetpack.param_list_compare(gather_state|default([])) }}"

- name: Run the platform discovery to determine engine
  include: "{{ item }}"
  with_first_found:
  - "includes/{{ ansible_network_os }}/platform_discovery.yaml"
  - "includes/unsupported_platform.yaml"


- name: Load the state gatherer
  include: "includes/load_gather.yaml"
  loop: "{{ gather }}"
  loop_control:
    loop_var: gather_one
