- name: "eos.lldp: show lldp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp neighbors"
        set_fact: True
        transform:
        - name: camel_to_snake
        - name: set_root_key
          key: "{{ fact_key }}"
