- name: "eos.mac: show mac address-table"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show mac address-table"
        set_fact: True
        transform:
        - name: camel_to_snake
        - name: set_root_key
          key: mac
        - name: set_root_key
          key: "{{ fact_key }}"
