---
- name: "nxos.fex: show fex"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show fex"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "fex"
        - name: set_root_key
          key: "{{ fact_key }}"
  when: not only_stats

- name: "nxos.fex: show fex detail"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show fex detail"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "detail"
        - name: set_root_key
          key: "fex"
        - name: set_root_key
          key: "{{ fact_key }}"
  when: not only_stats
