---
- name: "nxos.lldp_neighbors: show lldp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: stats
          only_stats: "{{ only_stats }}"
          keys:
          - l_port_id
        - name: "set_root_key"
          key: neighbors
        - name: "set_root_key"
          key: lldp
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.lldp_neighbors: show lldp all"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: stats
          only_stats: "{{ only_stats }}"
          keys:
          - lldp_dcbx
          - lldp_rx
          - lldp_tx
        - name: set_root_key
          key: interfaces
        - name: replace_keys
          keys:
          - before: '^lldp_all$'
            after: all
        - name: "set_root_key"
          key: lldp
        - name: set_root_key
          key: "{{ fact_key }}"
