---
- name: "nxos.vlan.private_vlan: show vlan private-vlan"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vlan private-vlan"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: private_vlan
        - name: set_root_key
          key: vlan
        - name: set_root_key
          key: "{{ fact_key }}"
