- name: "nxos.arp: show ip arp vrf all"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - ip
          - arp
          - vrf
          - all
          - nf:data
          - 'nf:rpc-reply'
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: arp
        - name: set_root_key
          key: "{{ fact_key }}"
