- name: "nxos.interfaces: show interface"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show interface"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: unnest
          keys:
          - __readonly__
          - show
          - interface
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface counters errors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show interface counters errors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: unnest
          keys:
          - __readonly__
          - show
          - interface
          - counters
          - errors
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: errors
        - name: set_root_key
          key: counters
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface switchport"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show interface switchport"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: unnest
          keys:
          - __readonly__
          - show
          - interface
          - switchport
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: switchport
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface transceiver"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show interface transceiver"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: unnest
          keys:
          - __readonly__
          - show
          - interface
          - transceiver
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: transceiver
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"
