- name: "nxos.lldp_neighbors: show lldp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    ignore_parser_errors: True
    commands:
      - command: "show lldp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - lldp
          - neighbors
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: neighbors
        - name: set_root_key
          key: lldp
        - name: set_root_key
          key: "{{ fact_key }}"


- name: "nxos.lldp_neighbors: show lldp neighbors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - lldp
          - all
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
          - before: '^lldp_all$'
            after: all
        - name: "set_root_key"
          key: lldp
        - name: set_root_key
          key: "{{ fact_key }}"
