---
- name: "nxos.mac: show mac address-table"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show mac address-table"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - mac
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: address_table
        - name: set_root_key
          key: mac
        - name: set_root_key
          key: "{{ fact_key }}"
