---
- name: "nxos.system: show system resources"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show hardware"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - system
          - resources
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: resources
        - name: set_root_key
          key: system
        - name: set_root_key
          key: "{{ fact_key }}"
