---
- name: "nxos.vlan: show vlan"
  nmake.jetpack.cli_parse_transform:
    engine: "native_xml"
    commands:
      - command: "show vlan"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: unnest
          keys:
          - __readonly__
          - show
          - vlan
          - nf:data
          - nf:rpc-reply
        - name: replace_keys
          keys:
          - before: '^@xmlns.*'
            after: ''
        - name: set_root_key
          key: vlan
        - name: set_root_key
          key: "{{ fact_key }}"
